<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.8" />
    <ProjectReference Include="../Githubie.Application/Githubie.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Githubie.Infrastructure.Tests" />
  </ItemGroup>
</Project>
