<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>githubie</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Githubie.Server/Githubie.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Githubie.Cli.Tests" />
  </ItemGroup>
</Project>
