<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.8" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Githubie.Application/Githubie.Application.csproj" />
    <ProjectReference Include="../Githubie.Infrastructure/Githubie.Infrastructure.csproj" />
    <ProjectReference Include="../Githubie.AskPass/Githubie.AskPass.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Githubie.Server.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
