<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0" />
    <PackageReference Include="FluentAssertions" Version="8.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Githubie.Domain/Githubie.Domain.csproj" />
  </ItemGroup>
</Project>
